# Generated by Django 5.0.3 on 2024-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabTrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=10)),
                ('heure_depart', models.TimeField()),
                ('destination', models.CharField(max_length=50)),
                ('voie', models.CharField(max_length=10)),
            ],
        ),
    ]
